feat: gstreamer removed
5G-ERA/era-5g-interface pull request #13
Opened 2023-06-29 06:39 UTC by klepo

Gstreamer is no longer used - big changes
H264 (pyav) used
Better named logger
Examples renamed (no http and gstreamer)

2023-07-06 09:32 UTC, ZdenekM requested changes

2023-07-06 09:32 UTC, ZdenekM commented on era_5g_interface/h264_decoder.py
> +        # try:
Remove commented code or add an explanation of why it is commented (if it is important stuff).

2023-07-06 09:32 UTC, ZdenekM commented on requirements.txt
> +av
There should be specific versions.

2023-07-06 09:32 UTC, ZdenekM commented on era_5g_interface/h264_encoder.py
> +        # self.encoder.options = {"crf": "0", "preset": "ultrafast", "tune": "zerolatency"}
Remove, make it an option, or document why it is commented if it makes sense to keep it here.

2023-07-06 09:32 UTC, ZdenekM commented on era_5g_interface/interface_helpers.py
> +    def store_latency(self, latency) -> None:
Add type annotation for `latency`.

2023-07-06 09:32 UTC, ZdenekM commented on era_5g_interface/interface_helpers.py
> +    def get_latencies(self):
Add type annotation.

2023-07-06 09:32 UTC, ZdenekM commented on era_5g_interface/interface_helpers.py
> +            except Exception as e:
Use some more specific exception, e.g., `HTTPError`.

2023-07-06 09:32 UTC, ZdenekM commented on era_5g_interface/interface_helpers.py
> +        # logger.info(f"Heart beat published to middleware: {data}")
remove

2023-07-10 11:32 UTC, klepo commented on era_5g_interface/h264_decoder.py
> +        for frame in self.decoder.decode(packet):
yes

2023-07-10 11:41 UTC, klepo commented on era_5g_interface/interface_helpers.py
> +    def get_latencies(self):
Any

2023-07-10 11:43 UTC, closed without merging